-- PostgreSQL schema v1; equivalent to SQLite v5 plus distributed records.
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS tasks (
                    id TEXT PRIMARY KEY, title TEXT NOT NULL, prompt TEXT NOT NULL, agent TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'draft', created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
                    result TEXT NOT NULL DEFAULT '', error TEXT NOT NULL DEFAULT '', steps INTEGER NOT NULL DEFAULT 0,
                    items TEXT NOT NULL DEFAULT '[]', pending TEXT NOT NULL DEFAULT '[]', owner_id TEXT NOT NULL DEFAULT 'owner', work_type TEXT);
CREATE TABLE IF NOT EXISTS events (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, task_id TEXT REFERENCES tasks(id), kind TEXT NOT NULL,
                    message TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS approvals (
                    id TEXT PRIMARY KEY, task_id TEXT NOT NULL REFERENCES tasks(id), call_id TEXT NOT NULL,
                    tool TEXT NOT NULL, arguments TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending',
                    created_at TEXT NOT NULL, decided_at TEXT, UNIQUE(task_id,call_id));
CREATE TABLE IF NOT EXISTS tool_runs (
                    task_id TEXT NOT NULL REFERENCES tasks(id), call_id TEXT NOT NULL,
                    tool TEXT NOT NULL, arguments TEXT NOT NULL, status TEXT NOT NULL,
                    result TEXT NOT NULL DEFAULT '', attempts INTEGER NOT NULL DEFAULT 1, PRIMARY KEY(task_id,call_id));
CREATE TABLE IF NOT EXISTS memory (key TEXT PRIMARY KEY, content TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS artifacts (
                    id TEXT PRIMARY KEY, task_id TEXT NOT NULL REFERENCES tasks(id), name TEXT NOT NULL,
                    content TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS schedules (
                    id TEXT PRIMARY KEY, name TEXT NOT NULL, prompt TEXT NOT NULL, agent TEXT NOT NULL,
                    interval_minutes INTEGER NOT NULL, enabled INTEGER NOT NULL DEFAULT 1,
                    next_run_at TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions (
                    token_hash TEXT PRIMARY KEY, csrf TEXT NOT NULL, expires DOUBLE PRECISION NOT NULL);
CREATE TABLE IF NOT EXISTS rate_limits (
                    key TEXT PRIMARY KEY, attempts INTEGER NOT NULL, resets DOUBLE PRECISION NOT NULL);
CREATE INDEX IF NOT EXISTS tasks_status ON tasks(status,created_at);
CREATE INDEX IF NOT EXISTS events_task ON events(task_id,id);
CREATE TABLE IF NOT EXISTS action_policy (id INTEGER PRIMARY KEY CHECK(id=1), revision INTEGER NOT NULL, document TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS policy_approvals (approval_id TEXT PRIMARY KEY REFERENCES approvals(id), fingerprint TEXT NOT NULL, expires DOUBLE PRECISION NOT NULL, signature TEXT NOT NULL, effect TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS policy_legacy (approval_id TEXT PRIMARY KEY REFERENCES approvals(id));
CREATE TABLE IF NOT EXISTS policy_usage (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, bucket TEXT NOT NULL, created_at DOUBLE PRECISION NOT NULL, calls INTEGER NOT NULL, cost INTEGER NOT NULL, recipients INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS policy_usage_window ON policy_usage(bucket,created_at);
CREATE TABLE IF NOT EXISTS security_domain (id INTEGER PRIMARY KEY CHECK(id=1), tenant TEXT NOT NULL, environment TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS credentials (name TEXT PRIMARY KEY, key_id TEXT NOT NULL, nonce BYTEA NOT NULL, ciphertext BYTEA NOT NULL, metadata TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS executions (
                    task_id TEXT PRIMARY KEY REFERENCES tasks(id), version INTEGER NOT NULL DEFAULT 1,
                    revision INTEGER NOT NULL DEFAULT 0, phase TEXT NOT NULL DEFAULT 'executing',
                    started_at TEXT NOT NULL, recoveries INTEGER NOT NULL DEFAULT 0,
                    model_failures INTEGER NOT NULL DEFAULT 0, final_text TEXT, verification TEXT);
CREATE TABLE IF NOT EXISTS plan_steps (
                    task_id TEXT NOT NULL REFERENCES tasks(id), action_id TEXT NOT NULL,
                    action_key TEXT NOT NULL, fingerprint TEXT NOT NULL, tool TEXT NOT NULL,
                    revision INTEGER NOT NULL, depends_on TEXT, status TEXT NOT NULL DEFAULT 'pending',
                    observation TEXT, PRIMARY KEY(task_id,action_id), UNIQUE(task_id,action_key));
CREATE TABLE IF NOT EXISTS webhook_receipts (delivery_id TEXT PRIMARY KEY, received DOUBLE PRECISION NOT NULL, task_id TEXT NOT NULL REFERENCES tasks(id));
CREATE TABLE IF NOT EXISTS model_routes (task_id TEXT PRIMARY KEY REFERENCES tasks(id), profile TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS model_calls (id TEXT PRIMARY KEY, task_id TEXT NOT NULL REFERENCES tasks(id), reserved_tokens INTEGER NOT NULL, reserved_micro_usd INTEGER NOT NULL, status TEXT NOT NULL, usage TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS schema_version (id INTEGER PRIMARY KEY CHECK(id=1), version INTEGER NOT NULL);
INSERT INTO schema_version VALUES (1,1) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS worker_leases (task_id TEXT PRIMARY KEY REFERENCES tasks(id), owner TEXT NOT NULL, fence BIGINT NOT NULL, expires DOUBLE PRECISION NOT NULL);
CREATE TABLE IF NOT EXISTS workers (id TEXT PRIMARY KEY, last_seen DOUBLE PRECISION NOT NULL);
CREATE TABLE IF NOT EXISTS artifact_objects (artifact_id TEXT PRIMARY KEY REFERENCES artifacts(id), object_key TEXT NOT NULL, sha256 TEXT NOT NULL);
CREATE OR REPLACE FUNCTION execution_task_phase_fn() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF NEW.status IN ('queued','waiting_approval','failed','cancelled') THEN
  UPDATE executions SET phase=NEW.status WHERE task_id=NEW.id;
 END IF;
 RETURN NEW;
END; $$;
CREATE OR REPLACE TRIGGER execution_task_phase AFTER UPDATE OF status ON tasks
FOR EACH ROW EXECUTE FUNCTION execution_task_phase_fn();
CREATE OR REPLACE FUNCTION queue_capacity_fn() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF NEW.status='queued' THEN
  IF (SELECT COUNT(*) FROM tasks WHERE status='queued') >= COALESCE(NULLIF(current_setting('a4g.queue_limit',true),''),'1000')::integer THEN
   RAISE EXCEPTION 'Work queue is full' USING ERRCODE='P0001';
  END IF;
 END IF;
 RETURN NEW;
END; $$;
CREATE OR REPLACE TRIGGER queue_capacity BEFORE INSERT OR UPDATE OF status ON tasks
FOR EACH ROW EXECUTE FUNCTION queue_capacity_fn();
